version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/lom
    ports:
      - "8000:8000"
    depends_on:
      - db

  
  db:
    image: postgres
    volumes:
      - ./db_volume:/var/lib/postgresql/data/
       
    env_file:
        - ./.env
  
  
  frontend:    
    build:
      context: ./frontend
      dockerfile: Dockerfile  
    
    ports:
      - "8081-8080"
    depends_on:
      - db

