# Generated by Django 3.2.9 on 2021-11-19 01:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Имя актера"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WriterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Имя актера")),
            ],
        ),
        migrations.CreateModel(
            name="MovieModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="heading of news"),
                ),
                (
                    "decsription",
                    models.TextField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="content of news article",
                    ),
                ),
                (
                    "imdb_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="movie genre",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="movie genre",
                    ),
                ),
                (
                    "director",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Имя актера"
                    ),
                ),
                (
                    "writers_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=250, verbose_name="array of writers names"
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "actors_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            max_length=250,
                            null=True,
                            verbose_name="array of actors names",
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actors",
                    models.ManyToManyField(
                        max_length=250,
                        to="movie.ActorModel",
                        verbose_name="actors relationship",
                    ),
                ),
                (
                    "writers",
                    models.ManyToManyField(
                        max_length=250,
                        to="movie.WriterModel",
                        verbose_name="writers relationship",
                    ),
                ),
            ],
        ),
    ]
