# Generated by Django 3.2.9 on 2021-11-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_auto_20211119_0240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviemodel",
            name="decsription",
            field=models.TextField(
                blank=True, max_length=500000, null=True, verbose_name="movie plot"
            ),
        ),
        migrations.AlterField(
            model_name="moviemodel",
            name="title",
            field=models.CharField(max_length=500, verbose_name="movie title"),
        ),
    ]
