# Generated by Django 3.2.9 on 2021-11-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20211119_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='movie rating'),
        ),
        migrations.AlterField(
            model_name='writermodel',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name of  writer'),
        ),
    ]
